application: hebkhan
version: 1
runtime: python27
api_version: 1
threadsafe: false
default_expiration: "365d"

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*\.orig
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*_test\.py
- ^(.*/)?sample_data/.*
- ^(.*/)?khan-exercises/test/.*
- ^(.*/)?presskit/.*
- ^(.*/)?deploy/.*
- ^(.*/)?javascript/testbase\.js
- ^(.*/)?.*_test\.html
- ^requirements\.txt
- ^agar
- ^testutil

handlers:
- url: /videos
  static_dir: ../../videos

- url: /flvplayer
  static_dir: flvplayer

- url: /stylesheets
  static_dir: stylesheets

- url: /favicon.ico
  static_files: images/favicon.ico
  mime_type: image/x-icon
  upload: images/favicon.ico

- url: /google663128d2a1a65b87.html
  static_files: google663128d2a1a65b87.html
  upload: google663128d2a1a65b87.html

- url: /images/favicon.ico
  static_files: images/favicon.ico
  mime_type: image/x-icon
  upload: images/favicon.ico

- url: /images
  static_dir: images

- url: /javascript
  static_dir: javascript

# Begin GTV integration
- url: /gtv/css
  static_dir: gtv/css

- url: /gtv/images
  static_dir: gtv/images

- url: /gtv/js
  static_dir: gtv/js

- url: /gtv/fullscreen.html
  static_files: gtv/fullscreen.html
  upload: gtv/fullscreen.html

- url: /gtv.*
  script: gtv.main.application
# End GTV integration

# Begin khan-exercises integration
- url: /khan-exercises/khan-exercise.js
  static_files: khan-exercises/khan-exercise.js
  upload: khan-exercises/khan-exercise.js

- url: /khan-exercises/utils
  static_dir: khan-exercises/utils

- url: /khan-exercises/css
  static_dir: khan-exercises/css

- url: /khan-exercises/images
  static_dir: khan-exercises/images

- url: /khan-exercises/(hashed.+\.js)
  static_files: khan-exercises/\1
  upload: khan-exercises/(hashed.+\.js)
# End khan-exercises integration

- url: /downloads/(.*)
  static_files: downloads/\1
  upload: downloads/(.*)

- url: /admin/.*
  script: main.application
  login: admin

- url: /api/.*
  script: api.main.application

- url: /gae_mini_profiler/static
  static_dir: gae_mini_profiler/static
  expiration: "300s"

- url: /gae_mini_profiler/.*
  script: gae_mini_profiler.main.application

- url: /gae_bingo/static
  static_dir: gae_bingo/static
  expiration: "300s"

- url: /gae_bingo/tests/.*
  script: gae_bingo.tests.main.application

- url: /gae_bingo/.*
  script: gae_bingo.main.application

- url: /gandalf/static
  static_dir: gandalf/static
  expiration: "300s"

- url: /gandalf/tests/.*
  script: gandalf.tests.main.application

- url: /gandalf?.*
  script: gandalf.main.application

- url: .*
  script: main.application

builtins:
- appstats: on
- deferred: on
- remote_api: on

inbound_services:
- warmup

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: django
  version: 1.4

includes:
- mapreduce/include.yaml

admin_console:
  pages:
    - name: AppStats
      url: /_ah/stats
    - name: Mapreduce
      url: /mapreduce
    - name: YouTube Sync
      url: /admin/youtubesync
